### ISSUE TITLE
Issue when installing and running dump-autoload

### ISSUE THREAD

**Issue by bland-industries** [Muetze42/nova-basic-package#5]
**Describe the bug**
I installed package `https://github.com/Muetze42/nova-menu` that uses this package. When I installed it the package and laravel ran `Illuminate\Foundation\ComposerScripts::postAutoloadDump` I got an error `Class "Illuminate\Foundation\Console\AboutCommand" not found`.

**To Reproduce**

1. `$ composer require norman-huth/nova-menu`
2. See error

**Expected behavior**
I would hope for no errors.

**Screenshots**
![image](https://github.com/Muetze42/nova-basic-package/assets/2641574/6a9acd8c-e742-4580-a044-9f92f3ec74eb)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Laravel Version: "v8.83.27"
 - Nova Version: "4.21.0"

**Comment by Muetze42** [comment]
Normally, the AboutCommand is a part of Laravel.

I have added a check if the class exists.

https://github.com/Muetze42/nova-basic-package/releases/tag/1.2.6
